
import React from 'react';
import {
  BarChart3, Box, Users, Settings, LogOut, Plus, Search, Download, Printer, Camera, Trash2, Edit, History, Clock, ArrowRight, Eye, Mail, Send, X, Lock, UserX, UserCheck, Key, User as UserIcon, ShieldCheck, RefreshCw, FileSpreadsheet, Filter, Layers, CheckCircle, Wrench, RotateCcw, XCircle, Database, LayoutGrid, MapPin, Phone, Building2, AlertTriangle, UserPlus, BrainCircuit, Activity
} from 'lucide-react';

export const BILINGUAL_LABELS = {
  name: "NOMBRE / NAME",
  part_name: "NOMBRE DEL COMPONENTE / PART NAME",
  brand: "MARCA / BRAND",
  model: "MODELO / MODEL",
  pn: "P/N (PART NUMBER)",
  sn: "S/N (SERIAL NUMBER)",
  date: "FECHA / DATE",
  tt: "T.T / TAT (TOTAL TIME)",
  tso: "TSO (TIME SINCE OVERHAUL)",
  trem: "T. REM (TIME REMAINING)",
  tc: "TC (TOTAL CYCLES)",
  cso: "CSO (CYCLES SINCE OVERHAUL)",
  crem: "C. REM (CYCLES REMAINING)",
  shelf_life: "VENCIMIENTO / SHELF LIFE",
  removal_reason: "RAZÓN DE REMOCIÓN / REMOVAL REASON",
  ac_removed: "REMOVIDO DE / REMOVED FROM (A/C)",
  position: "POSICIÓN / POSITION",
  report: "REPORTE TÉCNICO / TECHNICAL REPORT",
  rejection: "MOTIVO DE RECHAZO / REJECTION REASON",
  disposition: "DIPOSICIÓN FINAL / FINAL DISPOSITION",
  observations: "OBSERVACIONES / REMARKS",
  technician: "TÉCNICO / TECHNICIAN",
  inspector: "INSPECTOR",
  license: "LICENCIA / LICENSE",
  location: "UBICACIÓN / LOCATION",
  signature: "FIRMA / SIGNATURE",
  address: "DIRECCIÓN / ADDRESS",
  phone: "TELÉFONO / PHONE",
  email: "EMAIL",
  organization: "ORGANIZACIÓN / ORGANIZATION",
  physical_location: "LUGAR FÍSICO / PHYSICAL LOCATION"
};

export const TRANSLATIONS = {
  ES: {
    dashboard: "Estadísticas",
    inventory: "Inventario",
    users: "Usuarios",
    settings: "Configuración",
    logout: "Cerrar Sesión",
    search: "Buscar por P/N, S/N o Nombre...",
    yellow_tag: "MATERIAL APROBADO",
    green_tag: "MATERIAL REPARABLE",
    white_tag: "REMOVIDO SIN FALLA",
    red_tag: "MATERIAL RECHAZADO",
    add_part: "Ingresar Componente",
    save_print: "Guardar e Imprimir",
    location_title: "Ingresar Ubicación",
    location_placeholder: "Rack, Hangar, Gaveta...",
    technician: "Técnico",
    inspector: "Inspector",
    license: "Licencia",
    export_excel: "Exportar Excel",
    no_results: "No se encontraron resultados",
    language_toggle: "English",
    confirm_save: "Confirmar Ubicación y Guardar",
    stats_total: "Total de Componentes",
    stats_by_tag: "Cantidades por Tarjeta",
    stats_by_location: "Stock por Ubicación Física",
    stats_by_brand: "Análisis de Stock por Fabricante",
    granular_lookup: "Consulta Granular de Stock",
    granular_lookup_desc: "Ingrese un P/N para ver su desglose de inventario.",
    granular_search_placeholder: "Buscar por Part Number (P/N)...",
    lookup_pn_not_found: "P/N no encontrado en inventario.",
    lookup_total_stock: "Stock Total del Componente",
    lookup_in_stock: "EN INVENTARIO",
    export_toolbox: "Herramientas de Descarga",
    export_by_tag: "Descargar por Color",
    export_by_loc: "Descargar por Ubicación",
    export_all: "Descargar Inventario Total",
    history_title: "Historial de Movimientos",
    history_view: "Ver Historial",
    history_type: "Evento",
    history_prev_loc: "Ubicación Anterior",
    history_new_loc: "Ubicación Nueva",
    history_user: "Usuario",
    history_event_creation: "Registro Inicial",
    history_event_loc_change: "Cambio de Ubicación",
    history_event_status_change: "Cambio de Estado",
    history_event_update: "Actualización de Datos",
    view_part: "Detalles del Componente",
    send_email: "Enviar por Email",
    recipient_email: "Correo del Destinatario",
    email_placeholder: "ejemplo@aerolinea.com",
    send_button: "Enviar Reporte",
    email_success: "Correo enviado exitosamente",
    technical_details: "Detalles Técnicos",
    validation: "Validación y Firmas",
    suspend_user: "Suspender Cuenta",
    unsuspend_user: "Activar Cuenta",
    change_password: "Cambiar Contraseña",
    temp_password: "Contraseña Temporal",
    send_credentials: "Enviar credenciales por Email",
    must_change_pass_title: "Cambio de Contraseña Obligatorio",
    must_change_pass_desc: "Por seguridad, debe cambiar su contraseña temporal antes de continuar.",
    new_password: "Nueva Contraseña",
    confirm_password: "Confirmar Contraseña",
    save_password: "Actualizar Contraseña",
    user_suspended_label: "CUENTA SUSPENDIDA",
    login_title: "Terminal de Acceso",
    login_subtitle: "Gestión de Logística Aeronáutica",
    username: "Usuario",
    password: "Contraseña",
    login_button: "Ingresar al Sistema",
    forgot_password: "¿Olvidó su contraseña?",
    reset_password_title: "Resetear Contraseña",
    reset_password_desc: "Ingrese su correo electrónico para recibir instrucciones de recuperación.",
    send_reset_link: "Enviar Instrucciones",
    back_to_login: "Volver al inicio",
    login_error: "Credenciales inválidas o cuenta suspendida",
    reset_success: "Instrucciones enviadas. Revise su correo corporativo.",
    edit_user: "Editar Usuario",
    delete_user: "Eliminar Usuario",
    confirm_delete_user: "¿Está seguro de eliminar esta cuenta? Esta acción es irreversible.",
    create_user: "Crear Usuario",
    invite_user: "Invitar por Email",
    pass_mode_auto: "Generar Automática",
    pass_mode_manual: "Manual",
    password_label: "Contraseña de Acceso",
    gen_pass_notice: "La contraseña generada es:",
    copy_pass: "Copiar",
    copied: "¡Copiado!",
    reset_password_action: "Resetear Clave",
    send_new_creds: "Notificar por Email",
    password_complexity_error: "Seguridad insuficiente: Requiere 10+ caracteres, Mayúscula, Número y Símbolo Especial.",
    footer_certification: "Certifico que la parte identificada ha sido inspeccionada de acuerdo con las regulaciones de aviación civil vigentes. El instalador es responsable de verificar la elegibilidad de la parte.",
    footer_warning: "ADVERTENCIA: Este documento no constituye un retorno al servicio. Los datos técnicos deben ser verificados contra el manual de mantenimiento actual (AMM).",
    clear: "Limpiar",
    retake_photo: "Volver a capturar",
    upload_photo: "Subir Foto",
    capture: "Capturar",
    cancel: "Cancelar",
    reason_time: "TIEMPO CUMPLIDO",
    reason_failure: "FALLA",
    reason_condition: "CONDICIÓN",
    reason_other: "OTRO",
    reason_storage: "ALMACENAMIENTO",
    reason_troubleshooting: "CAZA FALLAS",
    verifying: "Verificando Protocolos...",
    login_encryption: "Cifrado de Extremo a Extremo Activo",
    login_security_notice: "Seguridad: El personal de soporte técnico nunca solicitará sus credenciales de acceso por email o teléfono.",
    login_footer_layer: "Logistics Terminal Secure Layer v4.0.1",
    select_lang: "Seleccione Idioma de Operación",
    operational_terminal: "Terminal Operativo v4.0",
    tech_certification_title: "Certificación Técnica",
    quality_inspector: "Inspector de Calidad",
    tech_responsible: "Técnico Responsable",
    digital_signature: "Firma Digital",
    inspection_stamp: "Sello de Inspección",
    invitation_sent: "Invitación enviada. El usuario podrá configurar su clave al ingresar.",
    lookup_by_location: "Búsqueda por Ubicación",
    lookup_by_type: "Búsqueda por Tipo de Parte",
    enter_location: "Rack, Hangar, Gaveta...",
    enter_part_type: "Ej: Motor, Batería, Actuador...",
    loc_not_found: "Ubicación no encontrada o vacía.",
    type_not_found: "Tipo de parte no encontrado.",
    finding_results: "Buscando resultados...",
    all_locations: "TODAS LAS UBICACIONES",
    total_stock_stock: "STOCK TOTAL",
    confirm_delete_part: "¿Confirmar eliminación del componente?",
    sign_here: "FIRMAR AQUÍ",
    stock_summary: "Resumen de Cantidades",
    actual_view: "Exportar Vista Actual",
    reason_assistance: "Auxilio",
    card_yellow: "AMARILLO",
    card_green: "VERDE",
    card_white: "BLANCO",
    card_red: "ROJO",
    form: {
      name: "NOMBRE",
      part_name: "NOMBRE DEL COMPONENTE",
      brand: "MARCA",
      model: "MODELO",
      pn: "P/N (PART NUMBER)",
      sn: "S/N (SERIAL NUMBER)",
      date: "FECHA",
      tt: "T.T / TAT (TIEMPO TOTAL)",
      tso: "TSO (TIEMPO DESDE OVERHAUL)",
      trem: "T. REM (TIEMPO REMANENTE)",
      tc: "TC (CICLOS TOTALES)",
      cso: "CSO (CICLOS DESDE OVERHAUL)",
      crem: "C. REM (CICLOS REMANENTES)",
      shelf_life: "VENCIMIENTO",
      removal_reason: "RAZÓN DE REMOCIÓN",
      ac_removed: "REMOVIDO DE (A/C)",
      position: "POSICIÓN",
      report: "REPORTE TÉCNICO",
      rejection: "MOTIVO DE RECHAZO",
      disposition: "DISPOSICIÓN FINAL",
      observations: "OBSERVACIONES",
      technician: "TÉCNICO",
      inspector: "INSPECTOR",
      license: "LICENCIA",
      location: "UBICACIÓN",
      signature: "FIRMA",
      address: "DIRECCIÓN",
      phone: "TELÉFONO",
      email: "EMAIL",
      organization: "ORGANIZACIÓN",
      physical_location: "LUGAR FÍSICO"
    }
  },
  EN: {
    dashboard: "Statistics",
    inventory: "Inventory",
    users: "Users",
    settings: "Settings",
    logout: "Logout",
    search: "Search by P/N, S/N or Name...",
    yellow_tag: "SERVICEABLE MATERIAL",
    green_tag: "REPAIRABLE MATERIAL",
    white_tag: "REMOVED NO DEFECT",
    red_tag: "REJECTED MATERIAL",
    add_part: "Add Component",
    save_print: "Save & Print",
    location_title: "Enter Location",
    location_placeholder: "Rack, Hangar, Drawer...",
    technician: "Technician",
    inspector: "Inspector",
    license: "License",
    export_excel: "Export Excel",
    no_results: "No results found",
    language_toggle: "Español",
    confirm_save: "Confirm Location & Save",
    stats_total: "Total Components",
    stats_by_tag: "Quantity by Tag",
    stats_by_location: "Stock by Physical Location",
    stats_by_brand: "Stock Analysis by Manufacturer",
    granular_lookup: "Granular Stock Lookup",
    granular_lookup_desc: "Enter a P/N to see its inventory breakdown.",
    granular_search_placeholder: "Search by Part Number (P/N)...",
    lookup_pn_not_found: "P/N not found in inventory.",
    lookup_total_stock: "Total Component Stock",
    lookup_in_stock: "IN STOCK",
    export_toolbox: "Download Tools",
    export_by_tag: "Download by Color",
    export_by_loc: "Download by Location",
    export_all: "Download Total Inventory",
    history_title: "Movement History",
    history_view: "View History",
    history_type: "Event",
    history_prev_loc: "Previous Location",
    history_new_loc: "New Location",
    history_user: "User",
    history_event_creation: "Initial Registration",
    history_event_loc_change: "Location Change",
    history_event_status_change: "Status Change",
    history_event_update: "Data Update",
    view_part: "Component Details",
    send_email: "Send by Email",
    recipient_email: "Recipient Email",
    email_placeholder: "example@airline.com",
    send_button: "Send Report",
    email_success: "Email sent successfully",
    technical_details: "Technical Details",
    validation: "Validation & Signatures",
    suspend_user: "Suspend Account",
    unsuspend_user: "Activate Account",
    change_password: "Change Password",
    temp_password: "Temporary Password",
    send_credentials: "Send credentials via Email",
    must_change_pass_title: "Mandatory Password Change",
    must_change_pass_desc: "For security reasons, you must change your temporary password to proceed.",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    save_password: "Update Password",
    user_suspended_label: "ACCOUNT SUSPENDED",
    login_title: "Access Terminal",
    login_subtitle: "Aviation Logistics Management",
    username: "Username",
    password: "Password",
    login_button: "Enter System",
    forgot_password: "Forgot password?",
    reset_password_title: "Reset Password",
    reset_password_desc: "Enter your email address to receive recovery instructions.",
    send_reset_link: "Send Instructions",
    back_to_login: "Back to login",
    login_error: "Invalid credentials or suspended account",
    reset_success: "Instructions sent. Check your corporate email.",
    edit_user: "Edit User",
    delete_user: "Delete User",
    confirm_delete_user: "Are you sure you want to delete this account? This action is irreversible.",
    create_user: "Create User",
    invite_user: "Invite via Email",
    pass_mode_auto: "Generate Auto",
    pass_mode_manual: "Manual Entry",
    password_label: "Access Password",
    gen_pass_notice: "Generated password is:",
    copy_pass: "Copy",
    copied: "Copied!",
    reset_password_action: "Reset Password",
    send_new_creds: "Notify via Email",
    password_complexity_error: "Weak security: Requires 10+ characters, Uppercase, Number and Special Symbol.",
    footer_certification: "I certify that the identified part has been inspected in accordance with current civil aviation regulations. The installer is responsible for verifying part eligibility.",
    footer_warning: "WARNING: This document does not constitute a return to service. Technical data must be verified against current Maintenance Manual (AMM).",
    clear: "Clear",
    retake_photo: "Retake photo",
    upload_photo: "Upload Photo",
    capture: "Capture",
    cancel: "Cancel",
    reason_time: "TIME COMPLIED",
    reason_failure: "FAILURE",
    reason_condition: "CONDITION",
    reason_other: "OTHER",
    reason_storage: "STORAGE",
    reason_troubleshooting: "TROUBLESHOOTING",
    verifying: "Verifying Protocols...",
    login_encryption: "End-to-End Encryption Active",
    login_security_notice: "Security: Support staff will never request your access credentials by email or phone.",
    login_footer_layer: "Logistics Terminal Secure Layer v4.0.1",
    select_lang: "Select Operating Language",
    operational_terminal: "Operational Terminal v4.0",
    tech_certification_title: "Technical Certification",
    quality_inspector: "Quality Inspector",
    tech_responsible: "Responsible Technician",
    digital_signature: "Digital Signature",
    inspection_stamp: "Inspection Stamp",
    invitation_sent: "Invitation sent. The user will be able to set their password upon login.",
    lookup_by_location: "Lookup by Location",
    lookup_by_type: "Lookup by Part Type",
    enter_location: "Rack, Hangar, Drawer...",
    enter_part_type: "e.g. Engine, Battery, Actuator...",
    loc_not_found: "Location not found or empty.",
    type_not_found: "Part type not found.",
    finding_results: "Finding results...",
    all_locations: "ALL LOCATIONS",
    total_stock_stock: "TOTAL STOCK",
    confirm_delete_part: "Confirm part deletion?",
    sign_here: "SIGN HERE",
    stock_summary: "Stock Summary",
    actual_view: "Export Current View",
    reason_assistance: "Assistance",
    card_yellow: "YELLOW",
    card_green: "GREEN",
    card_white: "WHITE",
    card_red: "RED",
    form: {
      name: "NAME",
      part_name: "PART NAME",
      brand: "BRAND",
      model: "MODEL",
      pn: "P/N (PART NUMBER)",
      sn: "S/N (SERIAL NUMBER)",
      date: "DATE",
      tt: "T.T / TAT (TOTAL TIME)",
      tso: "TSO (TIME SINCE OVERHAUL)",
      trem: "T. REM (TIME REMAINING)",
      tc: "TC (TOTAL CYCLES)",
      cso: "CSO (CYCLES SINCE OVERHAUL)",
      crem: "C. REM (CYCLES REMAINING)",
      shelf_life: "SHELF LIFE",
      removal_reason: "REMOVAL REASON",
      ac_removed: "REMOVED FROM (A/C)",
      position: "POSITION",
      report: "TECHNICAL REPORT",
      rejection: "REJECTION REASON",
      disposition: "FINAL DISPOSITION",
      observations: "REMARKS",
      technician: "TECHNICIAN",
      inspector: "INSPECTOR",
      license: "LICENSE",
      location: "LOCATION",
      signature: "SIGNATURE",
      address: "ADDRESS",
      phone: "PHONE",
      email: "EMAIL",
      organization: "ORGANIZATION",
      physical_location: "PHYSICAL LOCATION"
    }
  }
};

export const ICONS = {
  Dashboard: BarChart3, Inventory: Box, Users: Users, Settings: Settings, Logout: LogOut, Plus: Plus, Search: Search, Download: Download, Printer: Printer, Camera: Camera, Trash: Trash2, Edit: Edit, Yellow: CheckCircle, Green: Wrench, White: RotateCcw, Red: XCircle, History: History, Clock: Clock, ArrowRight: ArrowRight, Eye: Eye, Mail: Mail, Send: Send, X: X, Lock: Lock, UserX: UserX, UserCheck: UserCheck, Key: Key, User: UserIcon, Shield: ShieldCheck, Refresh: RefreshCw, Spreadsheet: FileSpreadsheet, Filter: Filter, Layers: Layers, Database: Database, Layout: LayoutGrid, XCircle: XCircle, ShieldCheck: ShieldCheck, MapPin: MapPin, Phone: Phone, Building: Building2, AlertTriangle, UserPlus, BrainCircuit, Activity
};
