version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hangar_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hangar
    volumes:
      - hangar_db_data_v3:/var/lib/postgresql/data:Z
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hangar"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hangar_net
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hangar_backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@db/${POSTGRES_DB:-inventory}
      FLASK_ENV: production
      # Resend API Key for Email Service
      RESEND_API_KEY: ${RESEND_API_KEY}
    volumes:
      - ./backend/app:/app/app:Z
      - ./backend/logs:/app/logs:Z
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hangar_net
    expose:
      - "5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hangar_frontend
    environment:
      VITE_API_URL: /api
      NODE_ENV: production
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    networks:
      - hangar_net
    expose:
      - "5173"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: hangar_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
    ports:
      - "8080:80"  # Mapped to 8080 for rootless compatibility
    depends_on:
      - backend
      - frontend
    networks:
      - hangar_net
    restart: always

volumes:
  hangar_db_data_v3:

networks:
  hangar_net:
    driver: bridge
