import React from 'react';
import { TagColor } from '../types';

interface ReportPDFTemplateProps {
    reportData: {
        reportId: string;
        reportType: string;
        generatedAt: string;
        generatedBy: string;
        summary: {
            total: number;
            byStatus: Record<string, number>;
            percentages: Record<string, number>;
        };
        data?: any[];
        groupedData?: Record<string, any[]>;
        filtersApplied?: Record<string, string>;
    };
    t: any;
}

const ReportPDFTemplate: React.FC<ReportPDFTemplateProps> = ({ reportData, t }) => {
    const data = reportData.data || Object.values(reportData.groupedData || {}).flat();
    const totalPages = Math.ceil(data.length / 25);
    const reportDate = new Date(reportData.generatedAt).toLocaleString();

    const getTagColorHex = (tag: string) => {
        switch (tag) {
            case 'YELLOW': return '#eab308';
            case 'GREEN': return '#10b981';
            case 'WHITE': return '#64748b';
            case 'RED': return '#f43f5e';
            default: return '#6366f1';
        }
    };

    const getReportTitle = () => {
        switch (reportData.reportType) {
            case 'TOTAL_INVENTORY': return 'REPORTE DE INVENTARIO TOTAL / TOTAL INVENTORY REPORT';
            case 'BY_STATUS': return 'REPORTE POR TIPO DE TARJETA / REPORT BY CARD TYPE';
            case 'BY_LOCATION': return 'REPORTE POR UBICACIÓN / REPORT BY LOCATION';
            case 'BY_PART_NUMBER': return 'REPORTE POR PART NUMBER / REPORT BY P/N';
            default: return 'AVIATION INVENTORY REPORT';
        }
    };

    // Split data into pages (25 items per page)
    const pages = [];
    for (let i = 0; i < data.length; i += 25) {
        pages.push(data.slice(i, i + 25));
    }

    return (
        <>
            <style>{`
        @page { size: A4; margin: 10mm; }
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .page-break { page-break-after: always; }
          .no-print { display: none !important; }
        }
      `}</style>

            {pages.map((pageData, pageIndex) => (
                <div key={pageIndex} className={`w-[210mm] mx-auto bg-white text-black font-sans ${pageIndex < pages.length - 1 ? 'page-break' : ''}`}>
                    {/* Header */}
                    <div className="border-b-4 border-black pb-3 mb-4">
                        <div className="flex justify-between items-start">
                            <div>
                                <h1 className="text-xl font-black tracking-tight">WORLD CLASS AVIATION</h1>
                                <p className="text-[8px] font-bold text-slate-100 uppercase tracking-widest">Aviation Technical Records & Logistics</p>
                            </div>
                            <div className="text-right">
                                <div className="border-2 border-black px-4 py-2 bg-slate-100">
                                    <p className="text-[10px] font-black uppercase">{getReportTitle()}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Report Metadata */}
                    <div className="grid grid-cols-12 gap-2 mb-4 text-[9px]">
                        <div className="col-span-4 border border-black p-2">
                            <span className="font-bold text-slate-500 block">REPORT ID:</span>
                            <span className="font-black">{reportData.reportId}</span>
                        </div>
                        <div className="col-span-4 border border-black p-2">
                            <span className="font-bold text-slate-500 block">GENERATED:</span>
                            <span className="font-black">{reportDate}</span>
                        </div>
                        <div className="col-span-4 border border-black p-2">
                            <span className="font-bold text-slate-500 block">GENERATED BY:</span>
                            <span className="font-black">{reportData.generatedBy}</span>
                        </div>
                    </div>

                    {/* Summary Stats (first page only) */}
                    {pageIndex === 0 && (
                        <div className="mb-4 border border-black">
                            <div className="bg-black text-white px-3 py-1">
                                <span className="text-[8px] font-black uppercase tracking-widest">SUMMARY / RESUMEN</span>
                            </div>
                            <div className="grid grid-cols-5 divide-x divide-black">
                                <div className="p-2 text-center">
                                    <p className="text-2xl font-black">{reportData.summary.total}</p>
                                    <p className="text-[7px] font-bold text-slate-100 uppercase">Total Items</p>
                                </div>
                                {Object.entries(reportData.summary.byStatus).map(([status, count]) => (
                                    <div key={status} className="p-2 text-center">
                                        <p className="text-xl font-black">{count}</p>
                                        <p className="text-[7px] font-bold uppercase" style={{ color: getTagColorHex(status) }}>
                                            {status}
                                        </p>
                                        <p className="text-[8px] font-mono text-slate-400">
                                            {reportData.summary.percentages[status] || 0}%
                                        </p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Data Table */}
                    <table className="w-full border-collapse text-[8px]">
                        <thead>
                            <tr className="bg-black text-white">
                                <th className="border border-black p-1 text-left font-black">STATUS</th>
                                <th className="border border-black p-1 text-left font-black">P/N</th>
                                <th className="border border-black p-1 text-left font-black">S/N</th>
                                <th className="border border-black p-1 text-left font-black">PART NAME</th>
                                <th className="border border-black p-1 text-left font-black">LOCATION</th>
                                <th className="border border-black p-1 text-left font-black">TAT/T.T</th>
                                <th className="border border-black p-1 text-left font-black">TSO</th>
                                <th className="border border-black p-1 text-left font-black">T.REM</th>
                            </tr>
                        </thead>
                        <tbody>
                            {pageData.map((item: any, idx: number) => (
                                <tr key={item.id || idx} className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
                                    <td className="border border-black p-1">
                                        <span
                                            className="px-1 py-0.5 text-[7px] font-black uppercase"
                                            style={{
                                                backgroundColor: `${getTagColorHex(item.tagColor)}20`,
                                                color: getTagColorHex(item.tagColor),
                                                border: `1px solid ${getTagColorHex(item.tagColor)}`
                                            }}
                                        >
                                            {item.tagColor}
                                        </span>
                                    </td>
                                    <td className="border border-black p-1 font-mono font-bold">{item.pn}</td>
                                    <td className="border border-black p-1 font-mono">{item.sn}</td>
                                    <td className="border border-black p-1 max-w-[120px] truncate">{item.partName}</td>
                                    <td className="border border-black p-1">{item.location}</td>
                                    <td className="border border-black p-1 font-mono">{item.ttTat || '—'}</td>
                                    <td className="border border-black p-1 font-mono">{item.tso || '—'}</td>
                                    <td className="border border-black p-1 font-mono">{item.trem || '—'}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    {/* Footer */}
                    <div className="mt-4 pt-3 border-t-2 border-black">
                        <div className="flex justify-between items-end">
                            {/* Signature Section */}
                            <div className="w-1/3">
                                <div className="border-t-2 border-black pt-2 mt-8">
                                    <p className="text-[8px] font-black uppercase text-center">RESPONSABLE DE INVENTARIO / INVENTORY MANAGER</p>
                                    <p className="text-[7px] text-slate-400 text-center mt-1">Firma / Signature</p>
                                </div>
                            </div>

                            {/* Page Number */}
                            <div className="text-[8px] font-bold text-slate-500">
                                <p>Page {pageIndex + 1} of {pages.length || 1}</p>
                            </div>

                            {/* Certification */}
                            <div className="text-right">
                                <p className="text-[6px] font-bold text-slate-400 max-w-[200px]">
                                    This document is generated automatically by the Aviation Inventory System.
                                    Data accuracy verified at time of generation.
                                </p>
                                <p className="text-[7px] font-mono text-slate-500 mt-1">
                                    {new Date().toISOString()}
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* Filters Applied (first page only) */}
                    {pageIndex === 0 && reportData.filtersApplied && Object.keys(reportData.filtersApplied).length > 0 && (
                        <div className="mt-2 text-[7px] text-slate-400">
                            <span className="font-bold">Filters Applied: </span>
                            {Object.entries(reportData.filtersApplied).map(([key, value]) => (
                                <span key={key} className="mr-2">{key}: {value}</span>
                            ))}
                        </div>
                    )}
                </div>
            ))}
        </>
    );
};

export default ReportPDFTemplate;
