/**
 * Report Export Utilities
 * 
 * CSV/Excel export with decimal precision and PDF print trigger
 * for aviation inventory reports.
 */

import { createRoot } from 'react-dom/client';
import React from 'react';
import ReportPDFTemplate from '../components/ReportPDFTemplate';

interface ReportData {
    reportId: string;
    reportType: string;
    generatedAt: string;
    generatedBy: string;
    filtersApplied?: Record<string, string>;
    data?: any[];
    groupedData?: Record<string, any[]>;
    summary: {
        total: number;
        byStatus: Record<string, number>;
        percentages: Record<string, number>;
    };
}

/**
 * Generate and download CSV file from report data.
 * Ensures decimal precision for aviation-critical fields (TAT/T.T, TSO, C.REM).
 */
export function generateReportCSV(reportData: ReportData, reportType: string): void {
    const data = reportData.data || Object.values(reportData.groupedData || {}).flat();

    if (data.length === 0) {
        alert('No data to export');
        return;
    }

    // Define CSV headers (bilingual)
    const headers = [
        'RECORD_ID',
        'STATUS / ESTADO',
        'P/N (PART NUMBER)',
        'S/N (SERIAL NUMBER)',
        'PART NAME / NOMBRE',
        'BRAND / MARCA',
        'MODEL / MODELO',
        'LOCATION / UBICACIÓN',
        'TAT / T.T',
        'TSO',
        'T.REM',
        'TC',
        'CSO',
        'C.REM',
        'REGISTRATION DATE / FECHA REGISTRO',
        'SHELF LIFE / VENCIMIENTO',
        'REMOVAL REASON / RAZÓN REMOCIÓN',
        'REJECTION REASON / MOTIVO RECHAZO',
        'TECHNICIAN / TÉCNICO',
        'INSPECTOR',
        'OBSERVATIONS / OBSERVACIONES'
    ];

    // Map data to CSV rows
    const rows = data.map((item: any) => [
        item.id || '',
        item.tagColor || '',
        item.pn || '',
        item.sn || '',
        escapeCSV(item.partName || ''),
        escapeCSV(item.brand || ''),
        escapeCSV(item.model || ''),
        escapeCSV(item.location || ''),
        formatDecimal(item.ttTat),
        formatDecimal(item.tso),
        formatDecimal(item.trem),
        formatDecimal(item.tc),
        formatDecimal(item.cso),
        formatDecimal(item.crem),
        item.registrationDate || '',
        item.shelfLife || '',
        escapeCSV(item.removalReason || ''),
        escapeCSV(item.rejectionReason || ''),
        escapeCSV(item.technicianName || ''),
        escapeCSV(item.inspectorName || ''),
        escapeCSV(item.observations || '')
    ]);

    // Add metadata header rows
    const metadataRows = [
        ['AVIATION INVENTORY REPORT'],
        ['Report ID', reportData.reportId],
        ['Report Type', reportData.reportType],
        ['Generated At', reportData.generatedAt],
        ['Generated By', reportData.generatedBy],
        ['Total Items', String(reportData.summary.total)],
        [''],
        ['FILTERS APPLIED:'],
        ...Object.entries(reportData.filtersApplied || {}).map(([key, value]) => [key, value]),
        [''],
        ['SUMMARY BY STATUS:'],
        ...Object.entries(reportData.summary.byStatus).map(([status, count]) => [
            status,
            String(count),
            `${reportData.summary.percentages[status] || 0}%`
        ]),
        [''],
        headers
    ];

    // Combine all rows
    const csvContent = [
        ...metadataRows.map(row => row.join(',')),
        ...rows.map(row => row.join(','))
    ].join('\n');

    // Create and download file
    const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    const filename = `${reportData.reportId}_${reportType}_${new Date().toISOString().split('T')[0]}.csv`;

    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Trigger browser print dialog with the PDF template.
 */
export function triggerReportPrint(reportData: ReportData, t: any): void {
    const printSection = document.getElementById('print-section');
    if (!printSection) {
        console.error('Print section not found');
        return;
    }

    printSection.innerHTML = '';
    const root = createRoot(printSection);

    // Set document title for PDF filename
    const oldTitle = document.title;
    document.title = `${reportData.reportId}_${reportData.reportType}`;

    root.render(React.createElement(ReportPDFTemplate, { reportData, t }));

    // Wait for render, then print
    setTimeout(() => {
        window.print();
        document.title = oldTitle;
    }, 1000);
}

// --- Helper Functions ---

/**
 * Escape CSV special characters
 */
function escapeCSV(value: string): string {
    if (!value) return '';
    // If value contains comma, newline, or quote, wrap in quotes
    if (value.includes(',') || value.includes('\n') || value.includes('"')) {
        return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
}

/**
 * Format numeric values with decimal precision.
 * Aviation standards require precise decimal values for times/cycles.
 */
function formatDecimal(value: string | number | null | undefined): string {
    if (value === null || value === undefined || value === '') {
        return '';
    }

    // If already a string with decimal notation, preserve it
    if (typeof value === 'string') {
        // Try to parse and format if it's a number string
        const num = parseFloat(value);
        if (!isNaN(num)) {
            // Preserve original precision if it's a decimal
            return value.includes('.') ? value : value;
        }
        return value;
    }

    // If it's a number, format with 2 decimal places
    if (typeof value === 'number') {
        return value.toFixed(2);
    }

    return String(value);
}
